name: vgma
description: An app for Vodafone Ghana Music Awards

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"




dependencies:
  flutter_local_notifications: ^1.4.4+2
  dotted_border: ^1.0.5
  provider: ^4.1.3
  intl: ^0.16.1
  flutter_svg: ^0.18.0
  slimy_card: ^1.0.4
  path_provider: ^1.5.1
  tweet_webview: ^0.2.2
  flutter_webview_plugin: ^0.3.11

  device_info: 0.4.0+3

  quiver: 2.1.3
  open_url: 1.0.1
  url_launcher: ^5.4.1
  equatable: ^1.1.0

  flash: ^1.1.0
  emojis: 0.8.1
  pigment: ^1.0.3
  fluttery_dart2: 0.0.9
  flutter_vector_icons: ^0.2.1
  simple_animations: ^1.3.6
  carousel_slider: ^1.4.1

  percent_indicator: ^2.1.1+1
  modal_bottom_sheet: ^0.1.6+1

  velocity_x: ^0.3.1
  device_preview: ^0.4.4

  color: ^2.1.1

  http: ^0.12.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  line_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter



  #dev_dependencies:
  #glob: 1.2.0
  #path: 1.8.0-nullsafety
  #translator: 0.1.4
  #intl_translation: 0.17.10
  #flutter_test:
   # sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/image/
    - assets/langs/
    - assets/user/
    - assets/thumbnails/
    - assets/ma-hfd/
    - assets/ma-skv/
    - assets/ma-hab/
    - assets/ma-asc/
    - assets/jewel1.png
    - assets/jewel2.png
    - assets/hof1.png
    - assets/hof2.png
    - assets/hof3.png
    - assets/hof4.png
    - assets/hof5.png
    - assets/vgma_hof.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300

    - family: Cairo
      fonts:
         - asset: assets/fonts/Cairo/Cairo-Regular.ttf
         - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Cairo/Cairo-Bold.ttf
           weight: 700
         - asset: assets/fonts/Cairo/Cairo-Black.ttf
           weight: 900

    - family: Billabong
      fonts:
         - asset: assets/fonts/Billabong.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

